In [1]:
import pandas as pd

In [8]:
dfNonJittered = pd.read_csv('../config/meta_apriori.csv', index_col=0)
dfJittered = pd.read_csv('../config/meta_apriori_jittered.csv', index_col=0)
# Rename loatitude and longitude columns in dfJittered
dfJittered.rename(columns={'latitude': 'latitude_jittered', 'longitude': 'longitude_jittered'}, inplace=True)
# Merge the two DataFrames on the index (assuming they have the same index)
dfMerged = pd.merge(dfNonJittered, dfJittered[['latitude_jittered', 'longitude_jittered']], left_index=True, right_index=True)
dfMerged

,Sample_ID,latitude,longitude,is_replicate,replicate,library,barcode,id,POP,latitude_jittered,longitude_jittered
0,ucin001,39.143365,-92.695926,False,NaN,14,ACCA,ucin001,MO,38.908602,-92.477809
1,ucin002,37.885845,-90.161531,False,NaN,15,ACCA,ucin002,MO,37.915594,-90.525565
2,ucin003,37.824835,-92.207022,False,NaN,16,ACCA,ucin003,MO,37.824835,-92.207022
3,ucin004conc,38.935162,-91.465437,False,NaN,9,AGTG,ucin004conc,MO,38.935162,-91.465437
4,ucin005,37.885845,-90.161531,False,NaN,10,AGTG,ucin005,MO,37.800541,-90.511032
...,...,...,...,...,...,...,...,...,...,...,...
334,ucin433,47.578635,-92.514570,False,NaN,33,AGAC,ucin433,MN_WI_ND,47.752345,-92.857395
335,ucin434,41.002049,-93.274419,False,NaN,33,ACCA,ucin434,IA_NE,41.002049,-93.274419
336,ucin435,41.822100,-90.578000,False,NaN,33,AGTG,ucin435,IA_NE,41.822100,-90.578000
337,ucin436,43.331593,-92.120109,False,NaN,33,CATC,ucin436,IA_NE,43.043452,-92.161399
338,ucin437,43.331593,-92.120109,False,NaN,33,GTGA,ucin437,IA_NE,43.532483,-92.406542

In [9]:
raw_df = pd.read_csv('../tables/raw_reads.csv')
deduped_df = pd.read_csv('../tables/deduped_reads.csv')
trimmed_df = pd.read_csv('../tables/trimmed_reads.csv')
aligned_df = pd.read_csv('../tables/aligned_reads.csv').drop(['aligned_reads'], axis=1)
reads_df = raw_df.merge(deduped_df, on='Sample_ID').merge(trimmed_df, on = 'Sample_ID').merge(aligned_df, on='Sample_ID')
reads_df

,Sample_ID,raw_reads,deduped_count,trimmed_count,aligned_0_times,aligned_exactly_once,aligned_more_than_once,overall_alignment_rate
0,ucin309,2082515,476417,476417,9524,398992,67901,0.9800
1,ucin301,2569876,538111,538111,10628,448413,79070,0.9802
2,ucin321,5319394,1074453,1074452,31950,887148,155354,0.9703
3,ucin330,999515,262282,262281,4355,217779,40147,0.9834
4,ucin379,7168214,1029049,1029046,21065,870022,137959,0.9795
...,...,...,...,...,...,...,...,...
334,ucin342re,48112,19209,19209,696,14516,3997,0.9638
335,ucin261replicate,351430,122158,122158,4719,97496,19943,0.9614
336,ucin415,192841,73655,73655,29657,35021,8977,0.5974
337,ucin349conc,306160,99372,99372,1075,80373,17924,0.9892
338,ucin431z,219453,75502,75502,5820,55916,13766,0.9229

In [10]:
dfReadsAndMetadata = dfMerged.merge(reads_df, on='Sample_ID')
dfReadsAndMetadata

,Sample_ID,latitude,longitude,is_replicate,replicate,library,barcode,id,POP,latitude_jittered,longitude_jittered,raw_reads,deduped_count,trimmed_count,aligned_0_times,aligned_exactly_once,aligned_more_than_once,overall_alignment_rate
0,ucin001,39.143365,-92.695926,False,NaN,14,ACCA,ucin001,MO,38.908602,-92.477809,3279546,604412,604412,6925,516779,80708,0.9885
1,ucin002,37.885845,-90.161531,False,NaN,15,ACCA,ucin002,MO,37.915594,-90.525565,3362150,623086,623086,22737,519603,80746,0.9635
2,ucin003,37.824835,-92.207022,False,NaN,16,ACCA,ucin003,MO,37.824835,-92.207022,2635930,538144,538144,9154,455349,73641,0.9830
3,ucin004conc,38.935162,-91.465437,False,NaN,9,AGTG,ucin004conc,MO,38.935162,-91.465437,20614903,1474391,1474390,761130,608518,104742,0.4838
4,ucin005,37.885845,-90.161531,False,NaN,10,AGTG,ucin005,MO,37.800541,-90.511032,11687962,1369235,1369235,345066,883952,140217,0.7480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,ucin433,47.578635,-92.514570,False,NaN,33,AGAC,ucin433,MN_WI_ND,47.752345,-92.857395,3348773,656800,656800,13212,551231,92357,0.9799
335,ucin434,41.002049,-93.274419,False,NaN,33,ACCA,ucin434,IA_NE,41.002049,-93.274419,1996692,496031,496031,56732,374163,65136,0.8856
336,ucin435,41.822100,-90.578000,False,NaN,33,AGTG,ucin435,IA_NE,41.822100,-90.578000,3670067,923570,923569,75938,733906,113725,0.9178
337,ucin436,43.331593,-92.120109,False,NaN,33,CATC,ucin436,IA_NE,43.043452,-92.161399,6681695,1055104,1055103,41707,880795,132601,0.9605
338,ucin437,43.331593,-92.120109,False,NaN,33,GTGA,ucin437,IA_NE,43.532483,-92.406542,1919700,470430,470430,7454,396837,66139,0.9842